ALTER TABLE fm_notification
    ADD COLUMN PROVIDER_MESSAGE_ID varchar(64) DEFAULT NULL AFTER LAST_ERROR,
    ADD KEY IDX_FM_NOTIFICATION_PROVIDER
        (CHANNEL_TYPE, DELIVERY_STATUS, PROVIDER_MESSAGE_ID);
