-- 將技術識別 BUSINESS_KEY 與使用者可讀 DOCUMENT_NUMBER 分離。
-- 既有正式單據只回填 DOCUMENT_NUMBER，不修改既有 Flowable / FlowMint business key。

ALTER TABLE fm_form_data
  ADD COLUMN IF NOT EXISTS DOCUMENT_NUMBER varchar(100) NULL AFTER BUSINESS_KEY;

ALTER TABLE fm_process_instance
  ADD COLUMN IF NOT EXISTS DOCUMENT_NUMBER varchar(100) NULL AFTER BUSINESS_KEY;

UPDATE fm_process_instance pi
JOIN fm_process_def pd
  ON pd.TENANT_ID = pi.TENANT_ID
 AND pd.PROCESS_DEF_ID = pi.PROCESS_DEF_ID
SET pi.DOCUMENT_NUMBER = pi.BUSINESS_KEY,
    pi.UUSERID = 'SYSTEM',
    pi.UDATE = NOW(3)
WHERE pd.DOCUMENT_TYPE IS NOT NULL
  AND pd.DOCUMENT_TYPE <> ''
  AND pi.DOCUMENT_NUMBER IS NULL;

UPDATE fm_form_data fd
JOIN fm_process_instance pi
  ON pi.TENANT_ID = fd.TENANT_ID
 AND pi.FORM_DATA_ID = fd.FORM_DATA_ID
SET fd.DOCUMENT_NUMBER = pi.DOCUMENT_NUMBER,
    fd.UUSERID = 'SYSTEM',
    fd.UDATE = NOW(3)
WHERE pi.DOCUMENT_NUMBER IS NOT NULL
  AND fd.DOCUMENT_NUMBER IS NULL;

ALTER TABLE fm_form_data
  ADD UNIQUE INDEX IF NOT EXISTS UK_FM_FORM_DATA_DOC_NO
    (TENANT_ID, DOCUMENT_NUMBER);

ALTER TABLE fm_process_instance
  ADD UNIQUE INDEX IF NOT EXISTS UK_FM_PI_DOC_NO
    (TENANT_ID, DOCUMENT_NUMBER);

SELECT COUNT(*) AS form_data_with_document_number
FROM fm_form_data
WHERE DOCUMENT_NUMBER IS NOT NULL;

SELECT COUNT(*) AS process_with_document_number
FROM fm_process_instance
WHERE DOCUMENT_NUMBER IS NOT NULL;
