ALTER TABLE fm_task_policy
  ADD COLUMN ALLOW_PARALLEL_ADD_SIGN char(1) NOT NULL DEFAULT 'N'
    AFTER ALLOW_ADD_SIGN,
  ADD COLUMN PARALLEL_ADD_SIGN_MAX_MEMBERS int NOT NULL DEFAULT 10
    AFTER ALLOW_PARALLEL_ADD_SIGN,
  ADD COLUMN PARALLEL_ADD_SIGN_COMMENT_REQUIRED char(1) NOT NULL DEFAULT 'Y'
    AFTER PARALLEL_ADD_SIGN_MAX_MEMBERS,
  ADD CONSTRAINT CK_FM_TP_PARALLEL_YN
    CHECK (
      ALLOW_PARALLEL_ADD_SIGN IN ('Y', 'N')
      AND PARALLEL_ADD_SIGN_COMMENT_REQUIRED IN ('Y', 'N')
    ),
  ADD CONSTRAINT CK_FM_TP_PARALLEL_MAX
    CHECK (PARALLEL_ADD_SIGN_MAX_MEMBERS BETWEEN 1 AND 20);

CREATE TABLE fm_task_parallel_add_sign (
  OID char(36) NOT NULL,
  TENANT_ID varchar(36) NOT NULL,
  PROCESS_INSTANCE_ID varchar(64) NOT NULL,
  PARENT_TASK_ID varchar(64) NOT NULL,
  TASK_DEFINITION_KEY varchar(100) NOT NULL,
  BATCH_NO int NOT NULL,
  REQUEST_KEY varchar(100) NOT NULL,
  STATUS varchar(20) NOT NULL,
  INITIATOR_ACCOUNT varchar(64) NOT NULL,
  REASON varchar(1000) NOT NULL,
  TOTAL_COUNT int NOT NULL,
  COMPLETED_COUNT int NOT NULL DEFAULT 0,
  AGREE_COUNT int NOT NULL DEFAULT 0,
  DISAGREE_COUNT int NOT NULL DEFAULT 0,
  FORM_SNAPSHOT_OID char(36) NOT NULL,
  STARTED_DATE datetime(3) NOT NULL,
  COMPLETED_DATE datetime(3) DEFAULT NULL,
  CANCELLED_DATE datetime(3) DEFAULT NULL,
  LOCK_VERSION int NOT NULL DEFAULT 0,
  CUSERID varchar(24) NOT NULL,
  CDATE datetime(3) NOT NULL,
  UUSERID varchar(24) DEFAULT NULL,
  UDATE datetime(3) DEFAULT NULL,
  PRIMARY KEY (OID),
  UNIQUE KEY UK_FM_TPAS_BATCH (
    TENANT_ID,
    PARENT_TASK_ID,
    BATCH_NO
  ),
  UNIQUE KEY UK_FM_TPAS_REQUEST (
    TENANT_ID,
    PARENT_TASK_ID,
    REQUEST_KEY
  ),
  KEY IDX_FM_TPAS_PARENT (
    TENANT_ID,
    PARENT_TASK_ID,
    STATUS
  ),
  CONSTRAINT CK_FM_TPAS_STATUS
    CHECK (STATUS IN ('WAITING', 'COMPLETED', 'CANCELLED')),
  CONSTRAINT CK_FM_TPAS_COUNTS
    CHECK (
      TOTAL_COUNT BETWEEN 1 AND 20
      AND COMPLETED_COUNT BETWEEN 0 AND TOTAL_COUNT
      AND AGREE_COUNT >= 0
      AND DISAGREE_COUNT >= 0
      AND AGREE_COUNT + DISAGREE_COUNT = COMPLETED_COUNT
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE fm_task_parallel_add_sign_member (
  OID char(36) NOT NULL,
  TENANT_ID varchar(36) NOT NULL,
  PARALLEL_ADD_SIGN_OID char(36) NOT NULL,
  MEMBER_ACCOUNT varchar(64) NOT NULL,
  FLOWABLE_TASK_ID varchar(64) DEFAULT NULL,
  STATUS varchar(20) NOT NULL,
  COMMENT varchar(1000) DEFAULT NULL,
  COMPLETED_DATE datetime(3) DEFAULT NULL,
  ORIGINAL_MEMBER_ACCOUNT varchar(64) NOT NULL,
  LOCK_VERSION int NOT NULL DEFAULT 0,
  CUSERID varchar(24) NOT NULL,
  CDATE datetime(3) NOT NULL,
  UUSERID varchar(24) DEFAULT NULL,
  UDATE datetime(3) DEFAULT NULL,
  PRIMARY KEY (OID),
  UNIQUE KEY UK_FM_TPASM_MEMBER (
    TENANT_ID,
    PARALLEL_ADD_SIGN_OID,
    MEMBER_ACCOUNT
  ),
  UNIQUE KEY UK_FM_TPASM_TASK (
    TENANT_ID,
    FLOWABLE_TASK_ID
  ),
  KEY IDX_FM_TPASM_BATCH_STATUS (
    TENANT_ID,
    PARALLEL_ADD_SIGN_OID,
    STATUS
  ),
  CONSTRAINT FK_FM_TPASM_BATCH
    FOREIGN KEY (PARALLEL_ADD_SIGN_OID)
    REFERENCES fm_task_parallel_add_sign (OID),
  CONSTRAINT CK_FM_TPASM_STATUS
    CHECK (
      STATUS IN (
        'PENDING',
        'AGREED',
        'DISAGREED',
        'REASSIGNED',
        'CANCELLED'
      )
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
