CREATE TABLE IF NOT EXISTS fm_process_category (
  OID char(36) NOT NULL,
  TENANT_ID varchar(36) NOT NULL,
  CATEGORY_CODE varchar(50) NOT NULL,
  CATEGORY_LABEL varchar(100) NOT NULL,
  ICON_CODE varchar(50) DEFAULT NULL,
  SORT_ORDER int NOT NULL DEFAULT 0,
  STATUS varchar(20) NOT NULL DEFAULT 'ACTIVE',
  CUSERID varchar(24) NOT NULL,
  CDATE datetime(3) NOT NULL,
  UUSERID varchar(24) DEFAULT NULL,
  UDATE datetime(3) DEFAULT NULL,
  PRIMARY KEY (OID),
  UNIQUE KEY UK_FM_PC_CODE (TENANT_ID, CATEGORY_CODE),
  KEY IDX_FM_PC_ACTIVE_SORT (TENANT_ID, STATUS, SORT_ORDER),
  CONSTRAINT CK_FM_PC_STATUS CHECK (STATUS in ('ACTIVE','INACTIVE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE fm_process_def
  ADD COLUMN IF NOT EXISTS PROCESS_SORT_ORDER int NOT NULL DEFAULT 0
  AFTER CATEGORY;

INSERT INTO fm_process_category
  (OID, TENANT_ID, CATEGORY_CODE, CATEGORY_LABEL, ICON_CODE, SORT_ORDER,
   STATUS, CUSERID, CDATE)
SELECT UUID(), pd.TENANT_ID, pd.CATEGORY, pd.CATEGORY, 'grid', 0,
       'ACTIVE', 'migration', NOW(3)
  FROM (
       SELECT DISTINCT TENANT_ID, CATEGORY
         FROM fm_process_def
        WHERE CATEGORY IS NOT NULL
          AND CATEGORY <> ''
  ) pd
 WHERE NOT EXISTS (
       SELECT 1
         FROM fm_process_category pc
        WHERE pc.TENANT_ID = pd.TENANT_ID
          AND pc.CATEGORY_CODE = pd.CATEGORY
   );

UPDATE fm_process_category
   SET CATEGORY_LABEL = '採購', ICON_CODE = 'cart', SORT_ORDER = 30,
       UUSERID = 'migration', UDATE = NOW(3)
 WHERE TENANT_ID = 'A01'
   AND CATEGORY_CODE = 'PURCHASE';

UPDATE fm_process_def
   SET PROCESS_SORT_ORDER = 10
 WHERE TENANT_ID = 'A01'
   AND PROCESS_KEY = 'FM_PURCHASE_APPROVAL';
