CREATE TABLE IF NOT EXISTS fm_attachment_upload_session (
    OID CHAR(36) NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    UPLOAD_SESSION_ID VARCHAR(36) NOT NULL,
    OWNER_ACCOUNT VARCHAR(100) NOT NULL,
    FORM_ID VARCHAR(36) NOT NULL,
    FORM_VERSION_NO INT NOT NULL,
    SESSION_STATUS VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    EXPIRES_DATE DATETIME(3) NOT NULL,
    CUSERID VARCHAR(24) NOT NULL,
    CDATE DATETIME(3) NOT NULL,
    UUSERID VARCHAR(24) NULL,
    UDATE DATETIME(3) NULL,
    PRIMARY KEY (OID),
    UNIQUE KEY UK_FM_ATTACHMENT_UPLOAD_SESSION
        (TENANT_ID, UPLOAD_SESSION_ID),
    KEY IDX_FM_ATTACHMENT_UPLOAD_OWNER
        (TENANT_ID, OWNER_ACCOUNT, SESSION_STATUS, EXPIRES_DATE),
    CONSTRAINT CK_FM_ATTACHMENT_UPLOAD_STATUS CHECK
        (SESSION_STATUS IN ('OPEN', 'BOUND', 'EXPIRED', 'CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fm_attachment_upload_file (
    OID CHAR(36) NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    ATTACHMENT_ID VARCHAR(36) NOT NULL,
    UPLOAD_SESSION_ID VARCHAR(36) NOT NULL,
    FIELD_KEY VARCHAR(100) NOT NULL,
    FILE_OID CHAR(36) NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    CONTENT_TYPE VARCHAR(100) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    CONTENT_SHA256 CHAR(64) NOT NULL,
    FILE_STATUS VARCHAR(20) NOT NULL DEFAULT 'TEMPORARY',
    SCAN_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CUSERID VARCHAR(24) NOT NULL,
    CDATE DATETIME(3) NOT NULL,
    UUSERID VARCHAR(24) NULL,
    UDATE DATETIME(3) NULL,
    PRIMARY KEY (OID),
    UNIQUE KEY UK_FM_ATTACHMENT_UPLOAD_FILE
        (TENANT_ID, ATTACHMENT_ID),
    KEY IDX_FM_ATTACHMENT_UPLOAD_SESSION_FILE
        (TENANT_ID, UPLOAD_SESSION_ID, FILE_STATUS),
    CONSTRAINT CK_FM_ATTACHMENT_UPLOAD_FILE_SIZE CHECK (FILE_SIZE > 0),
    CONSTRAINT CK_FM_ATTACHMENT_UPLOAD_FILE_STATUS CHECK
        (FILE_STATUS IN ('TEMPORARY', 'BOUND', 'DELETED')),
    CONSTRAINT CK_FM_ATTACHMENT_UPLOAD_SCAN_STATUS CHECK
        (SCAN_STATUS IN ('PENDING', 'CLEAN', 'INFECTED', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
