CREATE TABLE fm_ai_analysis (
    OID CHAR(36) NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    ANALYSIS_ID VARCHAR(36) NOT NULL,
    PROCESS_INSTANCE_ID VARCHAR(64) NOT NULL,
    TASK_ID VARCHAR(64) NOT NULL,
    TASK_DEF_KEY VARCHAR(100) NOT NULL,
    FORM_DATA_ID VARCHAR(36) NOT NULL,
    FORM_REVISION INT NOT NULL,
    ACTOR_ACCOUNT VARCHAR(24) NOT NULL,
    PROVIDER_CODE VARCHAR(50) NOT NULL,
    PROVIDER_TYPE VARCHAR(20) NOT NULL,
    MODEL_ID VARCHAR(100) NOT NULL,
    CONFIG_VERSION INT NOT NULL,
    PROMPT_TEMPLATE_VERSION INT NOT NULL,
    CONTENT_HASH CHAR(64) NOT NULL,
    GENERATION_NO INT NOT NULL,
    FORCE_REFRESH_FLAG CHAR(1) NOT NULL DEFAULT 'N',
    EXECUTION_STATUS VARCHAR(20) NOT NULL,
    ERROR_CODE VARCHAR(50) DEFAULT NULL,
    START_DATE DATETIME(3) NOT NULL,
    COMPLETE_DATE DATETIME(3) DEFAULT NULL,
    ELAPSED_MILLIS BIGINT DEFAULT NULL,
    INPUT_TOKENS INT DEFAULT NULL,
    OUTPUT_TOKENS INT DEFAULT NULL,
    RESULT_CONTENT LONGTEXT DEFAULT NULL,
    CUSERID VARCHAR(24) NOT NULL,
    CDATE DATETIME(3) NOT NULL,
    PRIMARY KEY (OID),
    UNIQUE KEY UK_FM_AI_ANALYSIS_ID (TENANT_ID, ANALYSIS_ID),
    UNIQUE KEY UK_FM_AI_ANALYSIS_GENERATION (
        TENANT_ID, CONTENT_HASH, GENERATION_NO
    ),
    KEY IDX_FM_AI_ANALYSIS_TASK (TENANT_ID, TASK_ID, EXECUTION_STATUS),
    KEY IDX_FM_AI_ANALYSIS_PROCESS (TENANT_ID, PROCESS_INSTANCE_ID, CDATE),
    CONSTRAINT CK_FM_AI_ANALYSIS_REFRESH CHECK (
        FORCE_REFRESH_FLAG IN ('Y', 'N')
    ),
    CONSTRAINT CK_FM_AI_ANALYSIS_STATUS CHECK (
        EXECUTION_STATUS IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED')
    ),
    CONSTRAINT CK_FM_AI_ANALYSIS_GENERATION CHECK (GENERATION_NO >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE fm_ai_analysis_access (
    OID CHAR(36) NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    ACCESS_ID VARCHAR(36) NOT NULL,
    ANALYSIS_ID VARCHAR(36) DEFAULT NULL,
    TASK_ID VARCHAR(64) NOT NULL,
    ACTOR_ACCOUNT VARCHAR(24) NOT NULL,
    ACCESS_TYPE VARCHAR(30) NOT NULL,
    RESULT_STATUS VARCHAR(20) NOT NULL,
    ERROR_CODE VARCHAR(50) DEFAULT NULL,
    REQUEST_DATE DATETIME(3) NOT NULL,
    CUSERID VARCHAR(24) NOT NULL,
    CDATE DATETIME(3) NOT NULL,
    PRIMARY KEY (OID),
    UNIQUE KEY UK_FM_AI_ANALYSIS_ACCESS_ID (TENANT_ID, ACCESS_ID),
    KEY IDX_FM_AI_ANALYSIS_ACCESS_TASK (
        TENANT_ID, TASK_ID, ACTOR_ACCOUNT, REQUEST_DATE
    ),
    KEY IDX_FM_AI_ANALYSIS_ACCESS_ANALYSIS (TENANT_ID, ANALYSIS_ID, REQUEST_DATE),
    CONSTRAINT CK_FM_AI_ANALYSIS_ACCESS_TYPE CHECK (
        ACCESS_TYPE IN (
            'CLICK', 'START', 'CACHE_HIT', 'READ', 'SUCCEEDED', 'FAILED'
        )
    ),
    CONSTRAINT CK_FM_AI_ANALYSIS_ACCESS_STATUS CHECK (
        RESULT_STATUS IN ('SUCCESS', 'FAILURE')
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
