CREATE TABLE IF NOT EXISTS fm_api_request (
    OID CHAR(36) NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    API_REQUEST_ID CHAR(36) NOT NULL,
    CLIENT_ID CHAR(36) NOT NULL,
    KEY_ID CHAR(36) NOT NULL,
    IDEMPOTENCY_KEY_HASH CHAR(64) NOT NULL,
    PAYLOAD_HASH CHAR(64) NOT NULL,
    PROCESS_DEF_ID VARCHAR(64) NOT NULL,
    PROCESS_VERSION_NO INT DEFAULT NULL,
    FORM_ID VARCHAR(64) NOT NULL,
    FORM_VERSION_NO INT DEFAULT NULL,
    FORM_SCHEMA_HASH CHAR(64) DEFAULT NULL,
    INITIATOR_ACCOUNT VARCHAR(64) NOT NULL,
    APPLICANT_ACCOUNT VARCHAR(64) NOT NULL,
    APPLICANT_ORG_UNIT_ID VARCHAR(64) DEFAULT NULL,
    SOURCE_SYSTEM VARCHAR(50) DEFAULT NULL,
    SOURCE_DOCUMENT_TYPE VARCHAR(50) DEFAULT NULL,
    SOURCE_DOCUMENT_NO VARCHAR(100) DEFAULT NULL,
    PROCESS_INSTANCE_ID VARCHAR(64) DEFAULT NULL,
    FLOWABLE_PROCESS_INSTANCE_ID VARCHAR(64) DEFAULT NULL,
    BUSINESS_KEY VARCHAR(100) DEFAULT NULL,
    DOCUMENT_NUMBER VARCHAR(100) DEFAULT NULL,
    FORM_DATA_ID VARCHAR(64) DEFAULT NULL,
    REQUEST_STATUS VARCHAR(20) NOT NULL DEFAULT 'PROCESSING',
    RESULT_CODE VARCHAR(50) DEFAULT NULL,
    SAFE_ERROR_MESSAGE VARCHAR(500) DEFAULT NULL,
    COMPLETED_AT DATETIME(3) DEFAULT NULL,
    LOCK_VERSION INT NOT NULL DEFAULT 0,
    CUSERID VARCHAR(24) NOT NULL,
    CDATE DATETIME(3) NOT NULL,
    UUSERID VARCHAR(24) DEFAULT NULL,
    UDATE DATETIME(3) DEFAULT NULL,
    PRIMARY KEY (OID),
    UNIQUE KEY UK_FM_API_REQUEST_ID (TENANT_ID, API_REQUEST_ID),
    UNIQUE KEY UK_FM_API_REQUEST_IDEMPOTENCY (
        TENANT_ID, CLIENT_ID, IDEMPOTENCY_KEY_HASH
    ),
    UNIQUE KEY UK_FM_API_REQUEST_EXTERNAL_REF (
        TENANT_ID, CLIENT_ID, SOURCE_SYSTEM,
        SOURCE_DOCUMENT_TYPE, SOURCE_DOCUMENT_NO
    ),
    KEY IDX_FM_API_REQUEST_PROCESS (TENANT_ID, PROCESS_INSTANCE_ID),
    KEY IDX_FM_API_REQUEST_BUSINESS (TENANT_ID, BUSINESS_KEY),
    KEY IDX_FM_API_REQUEST_DOCUMENT (TENANT_ID, DOCUMENT_NUMBER),
    KEY IDX_FM_API_REQUEST_STATUS (TENANT_ID, CLIENT_ID, REQUEST_STATUS, CDATE),
    CONSTRAINT CK_FM_API_REQUEST_STATUS CHECK (
        REQUEST_STATUS IN ('PROCESSING', 'SUCCEEDED', 'FAILED')
    ),
    CONSTRAINT CK_FM_API_REQUEST_PROCESS_VERSION CHECK (
        PROCESS_VERSION_NO IS NULL OR PROCESS_VERSION_NO >= 1
    ),
    CONSTRAINT CK_FM_API_REQUEST_FORM_VERSION CHECK (
        FORM_VERSION_NO IS NULL OR FORM_VERSION_NO >= 1
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
