CREATE TABLE fm_api_client (
    OID CHAR(36) NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    CLIENT_ID CHAR(36) NOT NULL,
    CLIENT_CODE VARCHAR(50) NOT NULL,
    CLIENT_NAME VARCHAR(100) NOT NULL,
    SYSTEM_TYPE VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(1000) DEFAULT NULL,
    ALLOWED_SCOPES LONGTEXT NOT NULL,
    ALLOWED_PROCESS_IDS LONGTEXT NOT NULL,
    ALLOWED_INITIATOR_ACCOUNTS LONGTEXT NOT NULL,
    IP_ALLOWLIST LONGTEXT NOT NULL,
    RATE_LIMIT_PER_MINUTE INT NOT NULL DEFAULT 60,
    DAILY_QUOTA INT NOT NULL DEFAULT 10000,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    LOCK_VERSION INT NOT NULL DEFAULT 0,
    CUSERID VARCHAR(24) NOT NULL,
    CDATE DATETIME(3) NOT NULL,
    UUSERID VARCHAR(24) DEFAULT NULL,
    UDATE DATETIME(3) DEFAULT NULL,
    PRIMARY KEY (OID),
    UNIQUE KEY UK_FM_API_CLIENT_ID (TENANT_ID, CLIENT_ID),
    UNIQUE KEY UK_FM_API_CLIENT_CODE (TENANT_ID, CLIENT_CODE),
    KEY IDX_FM_API_CLIENT_QUERY (TENANT_ID, STATUS, CLIENT_CODE),
    CONSTRAINT CK_FM_API_CLIENT_SYSTEM CHECK (
        SYSTEM_TYPE IN ('ERP', 'MES', 'HR', 'OTHER')
    ),
    CONSTRAINT CK_FM_API_CLIENT_STATUS CHECK (
        STATUS IN ('ACTIVE', 'INACTIVE')
    ),
    CONSTRAINT CK_FM_API_CLIENT_RATE CHECK (
        RATE_LIMIT_PER_MINUTE BETWEEN 1 AND 100000
    ),
    CONSTRAINT CK_FM_API_CLIENT_QUOTA CHECK (DAILY_QUOTA >= 1),
    CONSTRAINT CK_FM_API_CLIENT_SCOPES CHECK (JSON_VALID(ALLOWED_SCOPES)),
    CONSTRAINT CK_FM_API_CLIENT_PROCESSES CHECK (JSON_VALID(ALLOWED_PROCESS_IDS)),
    CONSTRAINT CK_FM_API_CLIENT_INITIATORS CHECK (
        JSON_VALID(ALLOWED_INITIATOR_ACCOUNTS)
    ),
    CONSTRAINT CK_FM_API_CLIENT_IPS CHECK (JSON_VALID(IP_ALLOWLIST))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE fm_api_client_key (
    OID CHAR(36) NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    CLIENT_ID CHAR(36) NOT NULL,
    KEY_ID CHAR(36) NOT NULL,
    KEY_PREFIX VARCHAR(32) NOT NULL,
    KEY_LAST_FOUR CHAR(4) NOT NULL,
    SECRET_HASH CHAR(64) NOT NULL,
    EFFECTIVE_FROM DATETIME(3) NOT NULL,
    EXPIRES_AT DATETIME(3) DEFAULT NULL,
    REVOKED_AT DATETIME(3) DEFAULT NULL,
    REVOKED_BY VARCHAR(24) DEFAULT NULL,
    REVOKE_REASON VARCHAR(1000) DEFAULT NULL,
    LAST_USED_AT DATETIME(3) DEFAULT NULL,
    LAST_SOURCE_IP VARCHAR(45) DEFAULT NULL,
    FAILED_COUNT INT NOT NULL DEFAULT 0,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    LOCK_VERSION INT NOT NULL DEFAULT 0,
    CUSERID VARCHAR(24) NOT NULL,
    CDATE DATETIME(3) NOT NULL,
    UUSERID VARCHAR(24) DEFAULT NULL,
    UDATE DATETIME(3) DEFAULT NULL,
    PRIMARY KEY (OID),
    UNIQUE KEY UK_FM_API_CLIENT_KEY_ID (KEY_ID),
    KEY IDX_FM_API_CLIENT_KEY_AUTH (TENANT_ID, KEY_ID, STATUS, EFFECTIVE_FROM, EXPIRES_AT),
    KEY IDX_FM_API_CLIENT_KEY_CLIENT (TENANT_ID, CLIENT_ID, STATUS),
    CONSTRAINT CK_FM_API_CLIENT_KEY_STATUS CHECK (
        STATUS IN ('ACTIVE', 'REVOKED', 'EXPIRED')
    ),
    CONSTRAINT CK_FM_API_CLIENT_KEY_FAILED CHECK (FAILED_COUNT >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE fm_api_access_log (
    OID CHAR(36) NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    ACCESS_ID CHAR(36) NOT NULL,
    CLIENT_ID CHAR(36) NOT NULL,
    KEY_ID CHAR(36) DEFAULT NULL,
    REQUEST_ID VARCHAR(64) NOT NULL,
    TRACE_ID VARCHAR(64) DEFAULT NULL,
    ENDPOINT_CODE VARCHAR(100) NOT NULL,
    REQUIRED_SCOPE VARCHAR(100) DEFAULT NULL,
    SOURCE_IP VARCHAR(45) NOT NULL,
    USER_AGENT_SUMMARY VARCHAR(255) DEFAULT NULL,
    HTTP_STATUS INT NOT NULL,
    RESULT_CODE VARCHAR(50) NOT NULL,
    ELAPSED_MILLIS BIGINT NOT NULL,
    REQUEST_BYTES BIGINT DEFAULT NULL,
    RESPONSE_BYTES BIGINT DEFAULT NULL,
    IDEMPOTENCY_KEY_HASH CHAR(64) DEFAULT NULL,
    PROCESS_INSTANCE_ID VARCHAR(64) DEFAULT NULL,
    BUSINESS_KEY VARCHAR(100) DEFAULT NULL,
    REQUEST_DATE DATETIME(3) NOT NULL,
    CUSERID VARCHAR(24) NOT NULL,
    CDATE DATETIME(3) NOT NULL,
    PRIMARY KEY (OID),
    UNIQUE KEY UK_FM_API_ACCESS_ID (TENANT_ID, ACCESS_ID),
    KEY IDX_FM_API_ACCESS_CLIENT (TENANT_ID, CLIENT_ID, REQUEST_DATE),
    KEY IDX_FM_API_ACCESS_REQUEST (TENANT_ID, REQUEST_ID),
    KEY IDX_FM_API_ACCESS_PROCESS (TENANT_ID, PROCESS_INSTANCE_ID, REQUEST_DATE),
    CONSTRAINT CK_FM_API_ACCESS_HTTP CHECK (HTTP_STATUS BETWEEN 100 AND 599),
    CONSTRAINT CK_FM_API_ACCESS_ELAPSED CHECK (ELAPSED_MILLIS >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
