-- FlowMint FM_PROG003D0002 - 工作代理程式註冊
-- 僅註冊程式資料；目前階段不配置角色權限，可重複執行。
START TRANSACTION;

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID,
     CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG003D', 'FC. FlowMint 簽核管理',
       '/', 'N', 'N', 0, 0,
       'CORE', 'FOLDER', 'ORGANIZATION', 'people',
       'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (
    SELECT 1
    FROM tb_sys_prog
    WHERE PROG_ID = 'FM_PROG003D'
);

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID,
     CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG003D0002Q', 'FC02 - 工作代理',
       '#/fm_prog003d0002', 'N', 'N', 0, 0,
       'CORE', 'ITEM', 'ORGANIZATION', 'people',
       'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (
    SELECT 1
    FROM tb_sys_prog
    WHERE PROG_ID = 'FM_PROG003D0002Q'
);

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID,
     CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG003D0002A', 'FC02 - 工作代理（新增）',
       '#/fm_prog003d0002/create', 'N', 'N', 0, 0,
       'CORE', 'ITEM', 'ORGANIZATION', 'people',
       'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (
    SELECT 1
    FROM tb_sys_prog
    WHERE PROG_ID = 'FM_PROG003D0002A'
);

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID,
     CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG003D0002E', 'FC02 - 工作代理（編輯）',
       '#/fm_prog003d0002/edit', 'Y', 'N', 0, 0,
       'CORE', 'ITEM', 'ORGANIZATION', 'people',
       'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (
    SELECT 1
    FROM tb_sys_prog
    WHERE PROG_ID = 'FM_PROG003D0002E'
);

COMMIT;