-- FlowMint FM_PROG002D0005 - 部門主管配置程式註冊
-- 僅註冊程式，不配置角色權限；請透過正式部署／資料庫變更程序執行。

START TRANSACTION;

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG002D0005Q', 'FB05 - 部門主管配置', '#/fm_prog002d0005',
       'N', 'N', 0, 0, 'CORE', 'ITEM', 'ORGANIZATION', 'person-badge',
       'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG002D0005Q');

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG002D0005A', 'FB05 - 部門主管配置（新增）', '#/fm_prog002d0005/create',
       'N', 'N', 0, 0, 'CORE', 'ITEM', 'ORGANIZATION', 'person-badge',
       'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG002D0005A');

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG002D0005E', 'FB05 - 部門主管配置（編輯）', '#/fm_prog002d0005/edit',
       'Y', 'N', 0, 0, 'CORE', 'ITEM', 'ORGANIZATION', 'person-badge',
       'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG002D0005E');

COMMIT;
