-- FlowMint FM_PROG002D0002 - 部門資料與組織樹程式註冊
-- 請透過正式部署／資料庫變更程序執行。

START TRANSACTION;

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG002D0002Q', 'FB02 - 部門資料與組織樹', '#/fm_prog002d0002',
       'N', 'N', 0, 0, 'CORE', 'ITEM', 'ORGANIZATION', 'diagram-2',
       'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (
    SELECT 1
      FROM tb_sys_prog
     WHERE PROG_ID = 'FM_PROG002D0002Q'
);

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG002D0002A', 'FB02 - 部門資料與組織樹（新增）', '#/fm_prog002d0002/create',
       'N', 'N', 0, 0, 'CORE', 'ITEM', 'ORGANIZATION', 'diagram-2',
       'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (
    SELECT 1
      FROM tb_sys_prog
     WHERE PROG_ID = 'FM_PROG002D0002A'
);

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG002D0002E', 'FB02 - 部門資料與組織樹（編輯）', '#/fm_prog002d0002/edit',
       'Y', 'N', 0, 0, 'CORE', 'ITEM', 'ORGANIZATION', 'diagram-2',
       'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (
    SELECT 1
      FROM tb_sys_prog
     WHERE PROG_ID = 'FM_PROG002D0002E'
);

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG002D0002T', 'FB02 - 部門組織樹', '#/fm_prog002d0002/tree',
       'N', 'N', 0, 0, 'CORE', 'ITEM', 'ORGANIZATION', 'diagram-2',
       'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (
    SELECT 1
      FROM tb_sys_prog
     WHERE PROG_ID = 'FM_PROG002D0002T'
);

COMMIT;
