-- FlowMint FM_PROG001D0001 - Tenant and account scope registration
-- Execute through the deployment/database change procedure.

START TRANSACTION;

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG001D', 'FA. FlowMint 基本設定', '/', 'N', 'N', 0, 0,
       'FM', 'FOLDER', 'PROPERTIES', 'gear-fill', 'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG001D');

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG001D0001Q', 'FA01 - Tenant 與帳號範圍', '#/fm_prog001d0001',
       'N', 'N', 0, 0, 'FM', 'ITEM', 'COMPANY', 'building', 'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG001D0001Q');

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG001D0001A', 'FA01 - Tenant 與帳號範圍（新增）', '#/fm_prog001d0001/create',
       'N', 'N', 0, 0, 'FM', 'ITEM', 'COMPANY', 'building-add', 'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG001D0001A');

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG001D0001E', 'FA01 - Tenant 與帳號範圍（編輯）', '#/fm_prog001d0001/edit',
       'Y', 'N', 0, 0, 'FM', 'ITEM', 'COMPANY', 'building-gear', 'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG001D0001E');

COMMIT;