-- FlowMint FM_PROG002D0004 - 職稱與簽核 Level 程式註冊
-- 請透過正式部署／資料庫變更程序執行。

START TRANSACTION;

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG002D0004Q', 'FB04 - 職稱與簽核 Level', '#/fm_prog002d0004',
       'N', 'N', 0, 0, 'CORE', 'ITEM', 'ORGANIZATION', 'diagram-3', 'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG002D0004Q');

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG002D0004A', 'FB04 - 職稱與簽核 Level（新增）', '#/fm_prog002d0004/create',
       'N', 'N', 0, 0, 'CORE', 'ITEM', 'ORGANIZATION', 'diagram-3', 'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG002D0004A');

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG002D0004E', 'FB04 - 職稱與簽核 Level（編輯）', '#/fm_prog002d0004/edit',
       'Y', 'N', 0, 0, 'CORE', 'ITEM', 'ORGANIZATION', 'diagram-3', 'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG002D0004E');

COMMIT;