-- FlowMint FM_PROG002D0001 - Employee management registration
-- Execute through the deployment/database change procedure.

START TRANSACTION;

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG002D', 'FB. FlowMint 組織管理', '/', 'N', 'N', 0, 0,
       'CORE', 'FOLDER', 'ORGANIZATION', 'diagram-3', 'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG002D');

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG002D0001Q', 'FB01 - 員工資料管理', '#/fm_prog002d0001',
       'N', 'N', 0, 0, 'CORE', 'ITEM', 'PEOPLE', 'people', 'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG002D0001Q');

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG002D0001A', 'FB01 - 員工資料管理（新增）', '#/fm_prog002d0001/create',
       'N', 'N', 0, 0, 'CORE', 'ITEM', 'PEOPLE', 'person-add', 'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG002D0001A');

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG002D0001E', 'FB01 - 員工資料管理（編輯）', '#/fm_prog002d0001/edit',
       'Y', 'N', 0, 0, 'CORE', 'ITEM', 'PEOPLE', 'person-gear', 'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG002D0001E');

COMMIT;
