-- FlowMint FM_PROG002D0003 - 組織簽核層級程式註冊
-- 請透過正式部署／資料庫變更程序執行。

START TRANSACTION;

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG002D0003Q', 'FB03 - 組織簽核層級', '#/fm_prog002d0003',
       'N', 'N', 0, 0, 'CORE', 'ITEM', 'ORGANIZATION', 'diagram-3', 'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG002D0003Q');

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG002D0003A', 'FB03 - 組織簽核層級（新增）', '#/fm_prog002d0003/create',
       'N', 'N', 0, 0, 'CORE', 'ITEM', 'ORGANIZATION', 'diagram-3', 'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG002D0003A');

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID, CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG002D0003E', 'FB03 - 組織簽核層級（編輯）', '#/fm_prog002d0003/edit',
       'Y', 'N', 0, 0, 'CORE', 'ITEM', 'ORGANIZATION', 'diagram-3', 'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG002D0003E');

COMMIT;
