-- FlowMint FM_PROG010D0002 - 外部系統 API 管理程式註冊
-- 本檔只註冊實際 UI Page，不配置角色權限，可重複執行。
START TRANSACTION;

UPDATE tb_sys_prog
   SET NAME = 'FJ. API-整合服務',
       UUSERID = 'admin',
       UDATE = CURRENT_TIMESTAMP
 WHERE PROG_ID = 'FM_PROG010D'
   AND NAME <> 'FJ. API-整合服務';

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID,
     CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG010D0002Q', 'FJ02 - 外部系統 API 管理',
       '#/fm_prog010d0002', 'N', 'N', 0, 0,
       'CORE', 'ITEM', 'ORGANIZATION', 'key',
       'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (
    SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG010D0002Q'
);

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID,
     CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG010D0002A', 'FJ02 - 外部系統 API 管理（新增）',
       '#/fm_prog010d0002/create', 'N', 'N', 0, 0,
       'CORE', 'ITEM', 'ORGANIZATION', 'key',
       'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (
    SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG010D0002A'
);

INSERT INTO tb_sys_prog
    (OID, PROG_ID, NAME, URL, EDIT_MODE, IS_DIALOG, DIALOG_W, DIALOG_H,
     PROG_SYSTEM, ITEM_TYPE, ICON, FONT_ICON_CLASS_ID,
     CUSERID, CDATE, UUSERID, UDATE)
SELECT UUID(), 'FM_PROG010D0002E', 'FJ02 - 外部系統 API 管理（編輯）',
       '#/fm_prog010d0002/edit', 'Y', 'N', 0, 0,
       'CORE', 'ITEM', 'ORGANIZATION', 'key',
       'admin', CURRENT_TIMESTAMP, NULL, NULL
WHERE NOT EXISTS (
    SELECT 1 FROM tb_sys_prog WHERE PROG_ID = 'FM_PROG010D0002E'
);

COMMIT;
